### ISSUE TITLE
Propose new setting types

### ISSUE THREAD

**Issue by vinistock** [vinistock/sail#11]
## Description

The idea of Sail is to be a centralized source of live configurations for Rails applications. More setting types can make the configurations simpler and require less application code to be written.

## Request

Propose new types of settings that could be useful having in Sail. Your proposal can either be a written idea as a comment in this issue or as a pull request implementing the new type.

Existing types can be found in the [readme].

[readme]: https://github.com/vinistock/sail/blob/master/README.md

**Comment by rohandaxini** [comment]
@vinistock This is an interesting gem (project) that you started. 

Just a thought:

How about `Date` and `Hash` types? I can raise a PR to add `Date` types to explain.

For example, in the case of `Date` settings, its ideally string configuration but if it can be directly converted to dates or datetime.

```ruby
TIMEAGO_DATE_TIME_FORMAT = "1 January 2000 at 12:30 PM"
NOTE_DATE_TIME_FORMAT    = "Jan 1, 2000 @ 12:30pm"
KALENDAE_DATE_FORMAT     = 'Apr 12, 2000'
```

**Comment by rohandaxini** [comment]
And `hash` configurations type could be

```ruby
SOCIAL_NETWORK = {
  'evernote'      => 'Evernote',
  'google_oauth2' => 'Google',
  'facebook_oauth' => 'Facebook'
```

**Comment by rohandaxini** [comment]
@vinistock This is an interesting gem (project) that you started. 

Just a thought: How about `Date` and `Hash` types? I can raise a PR to add `Date` types to explain.

Datetime or date configs would be ideally string configuration but I am wondering if it can be directly converted to `date` or `datetime`

For Example:
```ruby
TIMEAGO_DATE_TIME_FORMAT = "1 January 2000 at 12:30 PM"
NOTE_DATE_TIME_FORMAT    = "Jan 1, 2000 @ 12:30pm"
KALENDAE_DATE_FORMAT     = 'Apr 12, 2000'
```

And `hash` configurations type could be

```ruby
SOCIAL_NETWORK = {
  'evernote'      => 'Evernote',
  'google_oauth2' => 'Google',
  'facebook_oauth' => 'Facebook'
}
```

**Comment by vinistock** [comment]
@rohandaxini thanks for your interest in the project and for your suggestions!

The Date type should be pretty straight forward. You can just parse the string and it will throw an ArgumentError if it isn't valid. I think it will be a great addition.

About the Hash type: can you expand on possible use cases for this? What kind of live setting would be controlled by a Hash type? Furthermore, how do you picture this in the code? Keep a JSON string in the database and then parse it?

The only current limitation would be that the value field is a regular string and not text, which could not be enough to represent some hashes.

The Hash suggestion is also very interesting, I'm just trying to fully understand it.

**Comment by rohandaxini** [comment]
@vinistock 

`Date` type
Thanks for accepting my recommendation to add `Date` type. Yeah, that's correct, parse the string and throw `ArgumentError` is its invalid. I can raise a PR for same.

`Hash` type
Let's say we have a CSV or Excel to parse and import. We might want to map certain columns (attributes) of this CSV based and import it to application specific columns. This kind of mapping would be easier through a hash configuration. For example

```ruby
ABCD_IMPORT_MAPPING_HASH = {
  'Abcd Title'            =>  'Abcd_title',
  'Abcd Use with'    =>  'Abcd_use_with_name',
  'Abcd Tags'           =>  'Abcd_tags',
```
(Here `Abcd` represents some domain specific object)

**Comment by rohandaxini** [comment]
@vinistock 

`Date` type
Thanks for accepting my recommendation to add `Date` type. Yeah, that's correct, parse the string and throw `ArgumentError` if is its invalid. I can raise a PR for same. I think ill need to just make a change in this file `https://github.com/vinistock/sail/blob/master/app/models/sail/setting.rb` and in the documentation. Is that correct?

`Hash` type
Let's say we have a CSV or Excel to parse and import. We might want to map certain columns (attributes) of this CSV based and import it to application specific columns. This kind of mapping would be easier through a hash configuration. For example

```ruby
ABCD_IMPORT_MAPPING_HASH = {
  'Abcd Title'            =>  'Abcd_title',
  'Abcd Use with'    =>  'Abcd_use_with_name',
  'Abcd Tags'           =>  'Abcd_tags',
```
(Here `Abcd` represents some domain specific object)
