### ISSUE TITLE
Option to make pagination more compact

### ISSUE THREAD

**Issue by oleg-kiviljov** [vinistock/sail#152]
Currently if you have lot of settings the pagination takes too much space.

Here is an example of the issue:

![U9RTAEvA](https://user-images.githubusercontent.com/10065250/67089637-d4e7a600-f1b0-11e9-9a0a-9324d6df50a2.png)

Probably would be better to have the pagination in format < 1,2,3,4,5 ... > if the page number exceeds certain threshold.

**Comment by vinistock** [comment]
That makes sense. If there are more than 5 pages we should probably just display something like this (in this example for 10 pages):

```
< 1 2 3 4 5 ... 10 >
```

I'll work on a patch for the next release. Thanks for the issue!
