### ISSUE TITLE
Creating settings via YAML file causes webrick to break

### ISSUE THREAD

**Issue by vinistock** [vinistock/sail#36]
When using a YAML file to populate the database with settings, Sail adds a hook in the after initialize period. For some reason, this is breaking in webrick.

Issue #23 contains some more information.

**Comment by vinistock** [comment]
@rohandaxini Have you had issues with this again? I have not been able to reproduce it

**Comment by rohandaxini** [comment]
@vinistock I could not check it lately. I will let you know soon. Thanks.

**Comment by vinistock** [comment]
Closing the issue since there are no reports of it happening again.
