### ISSUE TITLE
Create A/B test cast type

### ISSUE THREAD

**Issue by vinistock** [vinistock/sail#4]
A/B test flags are useful for validating features live. Sail should support A/B testing out of the box.

### Expected behavior

When an ab_test setting has its value as 'true' in the database, the get method should randomly return true or false. This can easily be achieve using

```ruby
[true, false].sample
```

When an ab_test setting has its value as 'false' in the database, the get method should always return false (Boolean).

In summary, they are basically a Boolean setting, but when the value is 'true', it will randomize between true or false.

### Steps
- [x] Add ab_test to cast types in Setting class
- [x] In Setting.get, add logic to randomize true or false or always return false depending on setting value
- [x] Make sure ab_test settings are validated with ```value_is_true_or_false```
- [x] In the ```_setting.html.erb``` partial, make sure ab_test types are displayed exactly like Booleans

**Comment by vikasnautiyal** [comment]
Hi, I will pick this up.

**Comment by vinistock** [comment]
Resolved by #7 and cacab7cf7aa3e5e4b97421b7549b6579588c87b1
