### ISSUE TITLE
Please remove this 25 MB gif from Readme file

### ISSUE THREAD

**Issue by rokumatsumoto** [vinistock/sail#81]
https://raw.githubusercontent.com/vinistock/sail/master/README.md

**Comment by vinistock** [comment]
@rokumatsumoto The intent of the GIF was to have a simple demo of the engine. Is it causing you trouble loading the main page?

**Comment by rokumatsumoto** [comment]
@vinistock yes, i had noticeable lag experience when scrolling down. My user experience led me to block your gif. (uBlock)

**system info**
i have latest chrome

![xl80u-ojsq1-ojxnd-ps78l-vjqpi](https://user-images.githubusercontent.com/28678254/53869883-29ffee80-400a-11e9-8c88-a096e8b86799.png)

**Comment by vinistock** [comment]
@rokumatsumoto alright then. I will have to figure some other way to provide a short demo. I will replace the gif with an image again. Thanks for the issue report.
